# USER PARAMS
MAX_LEN_USER_EMAIL = 254
MAX_LEN_USER_USERNAME = 150
MAX_LEN_USER_LAST_NAME = 150
MAX_LEN_USER_FIRST_NAME = 150

# RECIPE PARAMS
MAX_LEN_RECIPE = 256


# INGREDIENTS PARAMS
MAX_LEN_INGREDIENTS = 128
