# Generated by Django 5.2 on 2025-05-10 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_shoopingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cookie_time",
            field=models.PositiveSmallIntegerField(
                help_text="Введите значение больше или равное 1",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Значение не может быть меньше 1!",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=14400,
                        message=(
                            "Максимальное значение",
                            "не может превышать 10 дней (14 400 минут)!",
                        ),
                    ),
                ],
                verbose_name="Время приготовления в минутах",
            ),
        ),
    ]
