# Generated by Django 5.2 on 2025-05-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_cookie_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cookie_time",
            new_name="cooking_time",
        ),
    ]
