# Generated by Django 5.2 on 2025-05-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_rename_cookie_time_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoopingcart",
            options={
                "default_related_name": "shopping_cart",
                "verbose_name": "Рецепт в корзине",
                "verbose_name_plural": "Рецепты в корзине",
            },
        ),
    ]
