# Generated by Django 5.2 on 2025-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "origin_url",
                    models.URLField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Исходная ссылка",
                    ),
                ),
                (
                    "short_url",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Короткая ссылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
            },
        ),
    ]
